# Density of Old Houses by Neighborhood

## By: Amy Zhang

##### Datasets: [Pre 1950 Housing Data](https://data.wprdc.org/dataset/pre-1950-housing/resource/afda23d8-ee01-4731-8419-6170149523a0) and [Neighborhoods](https://data.wprdc.org/dataset/neighborhoods2/resource/668d7238-cfd2-492e-b397-51a6e74182ff?inner_span=True)

#### First, load pandas, geopandas, fpsnippets (delete gpd if u dont use it)

In [2]:
import pandas as pd
import geopandas as gpd 
%matplotlib inline
import fpsnippets 
import zipfile
import os

In [2]:
#Load in Old Houses dataset
OldHouses= pd.read_csv("OlderHouses.csv")
OldHouses.head()

   _id  TRACT   Pre1950
0    1  10300  0.658477
1    2  20100  0.321088
2    3  20300  0.724907
3    4  30500  0.324117
4    5  40200  0.463549

#### neighborhood stuff

In [24]:
# need to get zip up in here. 
zip_file_path = 'pittsburghpaneighborhoods-.zip'  
extract_path = '/home/jupyter-ahz12/Group27' # i want my current working directory ofc

with zipfile.ZipFile(zip_file_path, 'r') as zip_refer:
    zip_refer.extractall(extract_path)
    
shapefile =  extract_path
neighborhoods = gpd.read_file(shapefile)
neighborhoods.head(3)

,OBJECTID,fid_blockg,statefp10,countyfp10,tractce10,blkgrpce10,geoid10,namelsad10,mtfcc10,funcstat10,...,created_us,created_da,last_edite,last_edi_1,temp,pghdb_sde_,GlobalID,Shape__Are,Shape__Len,geometry
0,1,233,42,003,140500,3,420031405003,Block Group 3,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,7968760.0,a642a6b6-a2a9-48d5-acf2-3e2ce87d4bc0,8.417066e+06,14181.728231,"POLYGON ((-79.90531 40.45549, -79.90488 40.455..."
1,2,203,42,003,140100,3,420031401003,Block Group 3,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,34078712.0,20d4605b-258e-441a-a57e-a28fdabb6d30,3.410838e+07,30326.729782,"POLYGON ((-79.92063 40.44423, -79.92052 40.443..."
2,3,86,42,003,101700,2,420031017002,Block Group 2,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,12751163.0,bf4065e7-c29c-48bd-b529-e7fd99077238,1.275115e+07,14577.426320,"POLYGON ((-79.93546 40.47257, -79.93530 40.472..."

In [16]:
current_working_directory = os.getcwd()
print("Current Working Directory:", current_working_directory)

Current Working Directory: /home/jupyter-ahz12/Group27

In [3]:
# csv version. not super helpful? because i cant use geopandas with this... BUT I COULD BE WRONG
neighborhoods = pd.read_csv("NeighborhoodGeoBounds.csv")
neighborhoods.head

#Separate columnsâ€“ I only want census tracts and hood names and other possibly usable spatial data
neighborhoods_ctracts = pd.DataFrame(columns=["CensusTracts", "GeoIds", "Neighborhoods","shape_area", "shape_length"])
neighborhoods_ctracts["CensusTracts"] = neighborhoods["tractce10"]
neighborhoods_ctracts["GeoIds"] = neighborhoods["geoid10"]
neighborhoods_ctracts["Neighborhoods"] = neighborhoods["hood"]
neighborhoods_ctracts["shape_area"] = neighborhoods["shape_area"]
neighborhoods_ctracts["shape_length"] = neighborhoods["shape_length"]
neighborhoods_ctracts.head()

  CensusTracts        GeoIds        Neighborhoods    shape_area  shape_length
0       140500  420031405003   Point Breeze North  8.417066e+06  14181.728231
1       140100  420031401003  Squirrel Hill North  3.410838e+07  30326.729782
2       101700  420031017002             Garfield  1.275115e+07  14577.426320
3       050900  420030509001    Bedford Dwellings  4.897512e+06  13941.514212
4       300100  420033001005            Knoxville  8.353056e+06  12021.864889

In [7]:
fpsnippets.geo_to_neighborhood(40.45064779643829, -79.93280624113156)

'Shadyside'

# Sidewalk to Street Ratios (Walkability)

## By: Amy Zhang

##### Dataset: [Sidewalk Street Ratio](https://data.wprdc.org/dataset/sidewalk-to-street-walkability-ratio/resource/b90ccee1-c0aa-43b9-93e2-8a25e690c393?inner_span=True) and [Neighborhoods](https://data.wprdc.org/dataset/neighborhoods2/resource/668d7238-cfd2-492e-b397-51a6e74182ff?inner_span=True)

In [11]:
# Load in walkability dataset
sidewalk_street_ratios = pd.read_csv("SidewalkStreeRatio.csv")
sidewalk_street_ratios.head()

# narrow down to relevant columns
walkability= pd.DataFrame(columns= ["GEOIDs","Ratios"])
walkability["GEOIDs"]= sidewalk_street_ratios["GEOID"]
walkability["Ratios"]= sidewalk_street_ratios["Ratio"]
walkability.head(3)

# I only want the ratios that are above 1 (more room for scurrying)
wideWalksOnly= walkability[walkability["Ratios"]>1.0]
wideWalksOnly.head(10)

# Sort by top values (descending, highest values at top)
wideWalksOnly.sort_values("Ratios", ascending = False)

# make a new dataframe with neighborhood names as an empty column
Neighborhood_Ratios= wideWalksOnly.DataFrame(columns= [""])

            GEOIDs    Ratios
696   420034773002  9.866193
29    420030509001  6.644908
1099  420039822001  4.045073
123   420031401003  3.615286
161   420031517006  3.447670
...            ...       ...
743   420034846002  1.015142
732   420034838001  1.009657
749   420034868002  1.005873
404   420034230002  1.001200
238   420032614001  1.000803

[464 rows x 2 columns]

In [25]:
#Load in neighborhoods shp file
zip_file_path = 'pittsburghpaneighborhoods-.zip'  
extract_path = '/home/jupyter-ahz12/Group27' # i want my current working directory ofc

with zipfile.ZipFile(zip_file_path, 'r') as zip_refer:
    zip_refer.extractall(extract_path)
    
shapefile =  extract_path
neighborhoods = gpd.read_file(shapefile)
neighborhoods.head(3)

,OBJECTID,fid_blockg,statefp10,countyfp10,tractce10,blkgrpce10,geoid10,namelsad10,mtfcc10,funcstat10,...,created_us,created_da,last_edite,last_edi_1,temp,pghdb_sde_,GlobalID,Shape__Are,Shape__Len,geometry
0,1,233,42,003,140500,3,420031405003,Block Group 3,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,7968760.0,a642a6b6-a2a9-48d5-acf2-3e2ce87d4bc0,8.417066e+06,14181.728231,"POLYGON ((-79.90531 40.45549, -79.90488 40.455..."
1,2,203,42,003,140100,3,420031401003,Block Group 3,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,34078712.0,20d4605b-258e-441a-a57e-a28fdabb6d30,3.410838e+07,30326.729782,"POLYGON ((-79.92063 40.44423, -79.92052 40.443..."
2,3,86,42,003,101700,2,420031017002,Block Group 2,G5030,S,...,SDE,2020-08-14,SDE,2020-08-14,None,12751163.0,bf4065e7-c29c-48bd-b529-e7fd99077238,1.275115e+07,14577.426320,"POLYGON ((-79.93546 40.47257, -79.93530 40.472..."

In [ ]:
#

In [27]:
# Narrow down to relevant columns
pitthoods= pd.DataFrame(columns= ["Neighborhoods","GeoIDs"])
pitthoods["GeoIDs"]= neighborhoods["geoid10"]
pitthoods["Neighborhoods"]= neighborhoods["hood"]
pitthoods.head(3)

         Neighborhoods        GeoIDs
0   Point Breeze North  420031405003
1  Squirrel Hill North  420031401003
2             Garfield  420031017002